observability: 
  deploy: true
  test-id: sample-test-id
  grafana–cloud:
    username: xxx
    password: xxx
    otlp-endpoint: xxx
manifests:
  path: manifest.yaml
  namespace: default
service:
  example-service-1:
    service-component:
      name: example-service-1
    deployment-component:
      name: example-service-1
      enabled: false
    virtual-service:
      transport: http
      protocol: grpc
      grpc:
        protofile-path: /proto/example.proto
        proto-service-name: exampleservice1
      path: /example-service-1.json
      enabled: true
      port: 5000
  example-service-2:
    service-component:
      name: example-service-2
    deployment-component:
      name: example-service-2
      enabled: true
    virtual-service:
      transport: http
      protocol: grpc
      grpc:
        protofile-path: /proto/example.proto
        proto-service-name: exampleservice2
      enabled: true
      port: 5001
      proxy: 
        auto-create: true
        save-result: true
        service-name: replaced-exampleservice2
