observability: 
  deploy: true
  test-id: sample-test-id
  grafana–cloud:
    username: xxx
    password: xxx
scenario:
  path: scenarios/example-scenario/index.js
service:
  example-service-1:
    service-component:
      name: exampleservice1
    deployment-component:
      name: exampleservice1
      enabled: false
    virtual-service:
      transport: http
      path: /virtual-services/example-service-1.json
      port: 5000
      enabled: false
  example-service-2:
    service-component:
      name: exampleservice2
    virtual-service:
      transport: http
      protocol: grpc
      grpc:
        protofile-path: /proto/demo.proto
        proto-service-name: exampleservice2
      enabled: true
      port: 5001
      proxy: 
        auto-create: true
        save-result: true
        service-name: replaced-exampleservice2
