apiVersion: v1
kind: Service
metadata:
  name: mountebank
  labels:
    app.kubernetes.io/name: mountebank
spec:
  ports:
  - name: http
    port: 2525
    targetPort: 2525
    appProtocol: http
  selector:
    app.kubernetes.io/name: mountebank